### ISSUE TITLE
  ImportError: cannot import name 'Lark' from 'lark' 

### ISSUE THREAD

**Issue by yuanjiale6** [eelxpeng/pyLTM#2]
Occurred  error "ModuleNotFoundError: No module named 'lark'  "
I tried run "pip install lark".    But it comes   "ImportError: cannot import name 'Lark' from 'lark' "

The logging info of error is as follows.

  File "../../pyLTM\pyltm\io\__init__.py", line 6, in <module>
    from .bifparser import BifParser
  File "../../pyLTM\pyltm\io\bifparser.py", line 7, in <module>
    from lark import Lark
ImportError: cannot import name 'Lark' from 'lark' (D:\Application\Anaconda3\lib\site-packages\lark\__init__.py)

**Comment by ASRodrigo1** [comment]
Uninstall lark: `pip uninstall lark`
Install lark-parser: `pip install lark-parser`
